# Generated by Django 2.2.7 on 2019-12-03 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('day_date', models.DateField(blank=True, null=True)),
                ('reflexy1', models.TextField()),
                ('reflexy2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('reward', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('goal1', models.TextField()),
                ('goal2', models.TextField()),
                ('goal3', models.TextField()),
                ('reflexy1', models.TextField()),
                ('reflexy2', models.TextField()),
                ('reflexy3', models.TextField()),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_complete', models.IntegerField()),
                ('is_main', models.IntegerField()),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('count_complete', models.IntegerField()),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_complete', models.IntegerField()),
                ('code_heirarchy', models.IntegerField()),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Day_habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.IntegerField()),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Day')),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Habit')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosmos.Week'),
        ),
    ]
