# Generated by Django 2.2.9 on 2020-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='reflexy1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='reflexy2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_begin',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='goal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='goal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='goal3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='reflexy1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='reflexy2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='reflexy3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
