# Generated by Django 2.2.9 on 2020-04-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='author',
        ),
    ]
